/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dMbsY95IQip
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import Link from "next/link"
import '../../app/style.css'
import { FaWhatsapp } from "react-icons/fa";

export function Main() {
  const [activeFilter, setActiveFilter] = useState("all")
  const projects = [
    {
      id: 1,
      title: "Residencial",
      category: "residencial",
      image: "/placeholder.svg?height=300&width=400",
    },
    {
      id: 2,
      title: "Comercial",
      category: "comercial",
      image: "/placeholder.svg?height=300&width=400",
    },
    {
      id: 3,
      title: "Institucional",
      category: "institucional",
      image: "/placeholder.svg?height=300&width=400",
    },
    {
      id: 4,
      title: "Residencial",
      category: "residencial",
      image: "/placeholder.svg?height=300&width=400",
    },
    {
      id: 5,
      title: "Comercial",
      category: "comercial",
      image: "/placeholder.svg?height=300&width=400",
    },
    {
      id: 6,
      title: "Institucional",
      category: "institucional",
      image: "/placeholder.svg?height=300&width=400",
    },
  ]
  const filteredProjects =
    activeFilter === "all" ? projects : projects.filter((project) => project.category === activeFilter)
  const testimonials = [
    {
      id: 1,
      name: "John Doe",
      quote: "The architect did an amazing job on our commercial project. Highly recommended!",
    },
    {
      id: 2,
      name: "Jane Smith",
      quote: "I am thrilled with the results of my residential project. The architect exceeded my expectations.",
    },
    {
      id: 3,
      name: "Michael Johnson",
      quote: "The architect's attention to detail and professionalism made our institutional project a success.",
    },
  ]
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary py-12 text-primary-foreground">
        <div className="container mx-auto px-4 md:px-6">
          <div className="flex flex-col items-center space-y-4 text-center">
            <h1 className="text-4xl font-bold">Ezequiel Schreiber, Arquitecto</h1>
            <p className="max-w-[600px] text-lg">
              John Doe is a renowned architect with over 20 years of experience in designing innovative and sustainable
              buildings. His portfolio includes a wide range of projects, from residential homes to commercial and
              institutional buildings.
            </p>
          </div>
        </div>
      </header>
      <main className="flex-1">
      <a href="https://wa.link/rn8264" className="float" target="_blank" id="wppIcon" >
      <FaWhatsapp size={35} color="#FFF" />
    </a>
        <section className="py-12 md:py-24">
          <div className="container mx-auto px-4 md:px-6">
            <div className="mb-8 flex justify-center">
              <Button
                variant={activeFilter === "all" ? "primary" : "outline"}
                onClick={() => setActiveFilter("all")}>
                All
              </Button>
              <Button
                variant={activeFilter === "residencial" ? "primary" : "outline"}
                onClick={() => setActiveFilter("residencial")}>
                Residencial
              </Button>
              <Button
                variant={activeFilter === "comercial" ? "primary" : "outline"}
                onClick={() => setActiveFilter("comercial")}>
                Comercial
              </Button>
              <Button
                variant={activeFilter === "institucional" ? "primary" : "outline"}
                onClick={() => setActiveFilter("institucional")}>
                Institucional
              </Button>
            </div>
            <div
              className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
              {filteredProjects.map((project) => (
                <div key={project.id} className="rounded-lg overflow-hidden">
                  <img
                    src="/placeholder.svg"
                    width={400}
                    height={300}
                    alt={project.title}
                    className="w-full h-auto object-cover"
                    style={{ aspectRatio: "400/300", objectFit: "cover" }} />
                  <div className="bg-card p-4">
                    <h3 className="text-lg font-bold">{project.title}</h3>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
        {/* <section className="bg-muted py-12 md:py-24">
          <div className="container mx-auto px-4 md:px-6">
            <div className="mb-8 text-center">
              <h2 className="text-3xl font-bold">What Our Clients Say</h2>
            </div>
            <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3">
              {testimonials.map((testimonial) => (
                <Card key={testimonial.id} className="p-6">
                  <blockquote className="text-muted-foreground">"{testimonial.quote}"</blockquote>
                  <div className="mt-4 text-right">
                    <p className="font-bold">{testimonial.name}</p>
                  </div>
                </Card>
              ))}
            </div>
          </div>
        </section> */}
        <section className="py-12 md:py-24">
          <div className="container mx-auto px-4 md:px-6 text-center">
            <h2 className="text-3xl font-bold mb-4">Ready to bring your vision to life?</h2>
            <p className="text-muted-foreground mb-8">Contact John Doe, Architect, to discuss your project.</p>
            <Link
              href="#"
              className="inline-flex items-center justify-center rounded-md bg-primary px-8 py-3 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
              prefetch={false}>
              Contact Us
            </Link>
          </div>
        </section>
      </main>
      <footer className="bg-muted py-6 text-muted-foreground">
        <div className="container mx-auto px-4 md:px-6 text-center">
          <p>&copy; 2024 Mizzio Coding. All rights reserved.</p>
        </div>
      </footer>
    </div>)
  );
}

export default Main;
